### PR TITLE
Feat: add OrderStatusReport

### PR DESCRIPTION
**Pull request by cs-simtrader**
Added an OrderStatusReport observer so that OrderStatus updates can be obtained. I couldn't see another way to do this so I emulated your services approach.

### CODE REVIEW

**Comment by dshe** [comment]
Thank you for your contribution.

After placing an order, **OpenOrder**, **OrderStatusReport**, and perhaps **OrderBound** objects are emitted.

These objects may also be requested using **RequestOpenOrders**, **RequestAllOpenOrders** and **RequestAutoOpenOrder(autoBind)**. In this case the objects are followed by **OpenOrdersEnd**. Please see **Services.CreateOpenOrdersObservable()**. Let me know if this helps.

**Comment by cs-simtrader** [comment]
I updated to the latest and tried using the OpenOrdersObservable and it doesn't appear to be passing on the OrderStatusReports.

**Comment by cs-simtrader** [comment]
[Fact]
    public async Task TestOrderStatus()
    {
        if (!Client.RemoteIPEndPoint.Port.IsIBDemoPort())
            throw new Exception("Cannot place order. Not the demo account");

        var requestId = Client.Request.GetNextRequestId();
        var orderId = Client.Request.GetNextOrderId();

        long statusReceived = 0;
        IObservable<object> orderStatusService = Client.Service.CreateOpenOrdersObservable();
        var orderStatusObserver = orderStatusService.Subscribe(async x =>
        {
            if (!(x is InterReact.OrderStatusReport))
                return;

            OrderStatusReport? status = x as InterReact.OrderStatusReport;

            if (status != null)
            {
                Interlocked.Increment(ref statusReceived);
                Logger.LogInformation("Status Received: ", status.Status);
            }
        });


        var taskOpenOrder = Client.Response
            .OfType<OpenOrder>()
            .Where(x => x.OrderId == orderId)
            .FirstAsync()
            .Timeout(TimeSpan.FromSeconds(5))
            .ToTask();


        var order = new Order
        {
            OrderId = orderId,
            OrderAction = OrderAction.Buy,
            TotalQuantity = 100,
            OrderType = OrderType.Limit,
            LimitPrice = 1 // below market
        };

        Client.Request.PlaceOrder(orderId, order, StockContract1);

        await taskOpenOrder;
        Client.Request.RequestAllOpenOrders();
        
        
       // cancel the order
        var taskCancelled = Client.Response
            .OfType<OrderStatusReport>()
            .Where(x => x.OrderId == orderId)
            .Where(x => x.Status == OrderStatus.Cancelled)
            .FirstAsync()
            .Timeout(TimeSpan.FromSeconds(5))
            .ToTask();

        Client.Request.CancelOrder(orderId);

        await taskCancelled;
       
        Client.Request.RequestAllOpenOrders();
        Thread.Sleep(4000);

        long lastValue = Interlocked.Read(ref statusReceived);
        if (lastValue == 0) 
        {
            throw new Exception("No order status received");
        }
        else
        {
            Logger.LogInformation("Number Status Reports Received: ", lastValue);
        }
    }

**Comment by cs-simtrader** [comment]
There should be "Submitted" and "Cancelled" OrderStatusReports generated when an order is posted and then cancelled.

**Pull request closed without merging**
